- name: RHEL for Edge Configuration Playbook
  hosts: localhost
  tasks:
    - name: Debug ansible_facts
      ansible.builtin.copy:
        content: "{{ ansible_facts }}"
        dest: /host/tmp/ansible_facts

    - name: Create Sudoers File for edge User
      ansible.builtin.copy:
        content: "{{ file_content }}"
        dest: /host/etc/sudoers.d/edge
      vars:
        file_content: |
          edge ALL=(ALL) NOPASSWD: ALL

    - name: Create OSTree Remote Repo
      ansible.builtin.copy:
        content: "{{ repo_content }}"
        dest: /host/etc/ostree/remotes.d/rfe-baseline.conf
      vars:
        repo_content: |
          [remote "rfe-baseline"]
          url=http://rfe-baseline-latest-edge-rhel9.apps.alice.lab.uc2.io/repo
          gpg-verify=false
          sign-verify=false
